---
- name: Prepare target drive for installation and bootstrap a linux filesystem on root partition
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/01_disk_partitioning.yml
    - import_tasks: tasks/02_btrfs_subvolumes.yml
    - import_tasks: tasks/03_hardware_configuration.yml
    - import_tasks: tasks/04_nixos_configuration.yml
    # - import_tasks: tasks/05_nixos_install.yml
